### ISSUE TITLE
Simplification

### ISSUE THREAD

**Issue by hindsholm** [platypusguy/FileDedupe#4]
Nice project and article!
I would like to suggest a simplification of the `DupesTable.insertFile()` method. It could be written as:
```java
public void insertFile( String filename, Long checksum ) {
    ArrayList<String> tableEntry = dupesTable.computeIfAbsent(checksum, c -> new ArrayList<>());
    tableEntry.add( filename );
}
```

**Comment by platypusguy** [comment]
Thanks for the kind words and excellent suggestion. Nicely done! I'm revising the table for the second article and  I'll be sure to use your improvement. Thanks again!
